services:
  # messaging-gateway:
    # image: messaging-gateway
    # container_name: messaging-gateway
    # ports:
      # - 8080:8080
  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
